### ISSUE TITLE
Stub repo empty

### ISSUE THREAD

**Issue by k42b3** [pinepain/php-v8#10]
Hi, first let me say that this project is really great. It looks like the repo for the php stubs (https://github.com/pinepain/php-v8-stubs) is empty so it is not possible to install the stubs through composer. I have played a bit with the extension and build a small lib (https://github.com/apioo/psx-v8) where I would like to use these stubs as composer dev dependency.

**Comment by pinepain** [comment]
Hi, thanks for the hint and sorry for later reply.

I planned to git subsplit stubs to separate repo and then update php-v8 repo, but was a bit busy with php-v8 itself. Later today I will publish stubs and add them to packagist.

**Comment by pinepain** [comment]
Fixed. Now you can just run `composer require --dev pinepain/php-v8-stubs` to require php-v8 stubs to your project.

**Comment by k42b3** [comment]
Great thx!
