### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ardabeyazoglu** [pinepain/php-v8#114]
Hi,

You've done a great work here. However, I just encountered the notice in [js-sandbox](https://github.com/phpv8/js-sandbox) repo, so I would like to know if this repo as well will be discontinued or not ?

**Comment by pinepain** [comment]
Hi, well, a "little bit" outdated response, but nope, unless someone want to sponsor the work on this repo, it is abandoned. It was fun, but I've moved on with other things so don't have time to play around with it.
