### ISSUE TITLE
V8\ObjectValue::SetAccessorProperty() corrupt

### ISSUE THREAD

**Issue by aight8** [pinepain/php-v8#12]
Following error I got:

```
Argument 2 passed to V8\ObjectValue::SetAccessorProperty() must be an instance of V8\Function, instance of Closure given
```

**Comment by pinepain** [comment]
Hi! Thanks for the report. It's a buggy stubs and parameter type hint, in V8\ObjectValue::SetAccessorProperty() getter should be `V8\FunctionObject`, not `callable` or nonexistent `V8\Function` class. I'll fix that later today.

**Comment by pinepain** [comment]
Should be fixed in master now.
