### ISSUE TITLE
FunctionObject::IsConstructor

### ISSUE THREAD

**Issue by aight8** [pinepain/php-v8#13]
While I want to check if a JS function is a constructor I got this error:

```
Error
Call to undefined method V8\FunctionObject::IsConstructor()
```

Input:
```
class TestClass {
  testMe() {
    console.log('test me!!!');
  }
}

TestClass
```

Used the return value.

**Comment by pinepain** [comment]
Hi Sebastian! Thanks for the report. 

Bug confirmed. `V8\FunctionObject` should inherit `V8\ObjectValue` where `IsConstructor()` method is defined itself. Will fix asap and verify whether other classes affected.

**Comment by pinepain** [comment]
Hi Sebastian! Thanks for the report. 

Can you please provide minimal reproducible problem? Also, please, specify `php -v` and `php --ri v8` output. [Tests](https://github.com/pinepain/php-v8/blob/6e537e4de5092c9a3e90fbfc2d986e9a1b4e82c1/tests/V8FunctionObject.phpt#L125) shows that it should work, so it looks like some bug.

**Comment by pinepain** [comment]
@aight8 can you provide some more details as described above?

**Comment by pinepain** [comment]
Closing as there was no response for two weeks and I can't reproduce the issue, so considering it is not relevant anymore or local problem/typo. If the problem will occurs again, please, fill separate issue.
