### ISSUE TITLE
Distinguish number between int and float

### ISSUE THREAD

**Issue by k42b3** [pinepain/php-v8#19]
Hi, I have the case where I define javascript code which defines a `number` and on the PHP side I have to differentiate whether the value is an int or float. At the moment all defined numbers are float. I have looked a bit in the source and the check whether to return an integer or float from a number is already implemented (`php_v8_value.cc:268`) but commented. Do you have plans to activate this detection? Otherwise I have to perform this check on the PHP side with something like `strpos('.', $value) === false ? (int) $value : $value` which I think is not the best solution.

**Comment by pinepain** [comment]
Hi, thanks for noticing!

I was not sure how good it would be when you pass `NumberValue` object with value, say,  withing `uint32` range and get back `Uint32Value` object.

Though later I also faces a need to somehow differ float from int. As I'm currently doing some wild changes on php-v8 so I will cover this issue in one of commits.

**Comment by pinepain** [comment]
FTR, [psx-v8/composer.json](https://github.com/apioo/psx-v8/blob/96d64cca6c26c862b3e110379664e2dfc5b1c131/composer.json#L15): if you do mean to require php-v8, it requires PHP >= 7.0, so I'd suggest to specify `"php": ">=5.5"`, like in [php-v8-stubs/composer.json](https://github.com/pinepain/php-v8-stubs/blob/15156e156c74ce9ae8a238494ebc4e2f61ddfec2/composer.json#L16).

**Comment by k42b3** [comment]
Thx for the info and the fix. Regarding the `composer.json` I have another project which requires this package and where the v8 engine is only a "nice" feature but not required for project to work. So users can still install it under 5.6. without v8. If they have PHP >= 7.0 they can also install the extension and use the v8 engine. This is only the reason for this "wrong" version constraint. But I will probably drop soon the 5.6 support thus I can set the correct constraint.

**Comment by k42b3** [comment]
Hi, thx for the fix! Do you have roughly any time plan for a first stable version or are there plans for any huge BC breaks. I think the current API looks really great.

**Comment by pinepain** [comment]
0.1.2 was just released and it has numerous BC breaks, though it's less likely you'll be affected, see [release notice](https://github.com/pinepain/php-v8/releases/tag/0.1.2) for details.

There will be more upcoming BC-breaking changes in forseable future, not specific details at this time, but it will be API simplification and performance tuning.
