### ISSUE TITLE
Unable to load dynamic library

### ISSUE THREAD

**Issue by k42b3** [pinepain/php-v8#21]
Hi, I have updated the php-v8 extension to the latest version on ubuntu:

    Get:1 http://ppa.launchpad.net/pinepain/php/ubuntu xenial/main amd64 php-v8 amd64 0.1.2-ppa1~xenial [155 kB]
    Fetched 155 kB in 0s (515 kB/s)
    (Reading database ... 323709 files and directories currently installed.)
    Preparing to unpack .../php-v8_0.1.2-ppa1~xenial_amd64.deb ...
    Unpacking php-v8 (0.1.2-ppa1~xenial) over (0.1.1-ppa1~xenial) ...
    Setting up php-v8 (0.1.2-ppa1~xenial) ...

Now I get the following warning everytime I run a PHP script:

    PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/v8.so' - libv8_libplatform.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by pinepain** [comment]
Hi! Thanks for reporting.

I missed to specify libv8 as a runtime requirement, so it wasn't installing automatically. I uploaded fixed release, `0.1.2.1`. Please, upgrade or just run `sudo apt-get install libv8-5.8.172` (necessary libv8 is already in the same pinepain/php PPA).

**Comment by k42b3** [comment]
Hi, thanks for the quick fix! Now everything works fine.
