### ISSUE TITLE
PPA releases

### ISSUE THREAD

**Issue by k42b3** [pinepain/php-v8#27]
Hi, I have a short question regarding the [php-v8 ppa](https://launchpad.net/~pinepain/+archive/ubuntu/php-v8). Iam using this ppa in a docker image which automatically installs this extension. It uses a fixed version i.e. `0.1.3.1-ppa1~xenial` unfortunately if you release a new version it is not possible to install an older version anymore. Basically my docker file looks like:

```
ENV PHPV8_VERSION "0.1.3.1-ppa1~xenial"

RUN add-apt-repository -y ppa:pinepain/php
RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install php-v8=${PHPV8_VERSION}
```

I have updated now my dockerfile to `0.1.6-ppa1~xenial` and everything works fine. But is there a way to install older versions so that my dockerfile does not break directly if you release a new version?

**Comment by pinepain** [comment]
@k42b3 Hi, thanks for bringing it up.

First of all, sorry if my releases break your code, there was many BC-incompatible changes. While by semantic version it's allowed, as a developer I know what PITA it is to clean up after every BC break. It's not a solution, but to keep informed about upcoming changes I'd suggest you to watch this repo, I try to publish detailed list of changes in every PR and every release, so you'd have better perspective about what goes on.

After last wild and massive BC-breaks I don't think I will have to introduce more such breaks in foreseeable future, but don't rely on this 😄 , as long as it's a development version (0.y.z), if I will find any bug or misleading functionality which requires harsh BC break, I'd prefer to fix it.

As to your question about installing older versions: unfortunately, I didn't find a way to do that at the moment, at least in a straightforward way.

**Creating and maintaining your own PPA could be a further solution to the problem**. You can simply copy exact versions you want to use and then stick ot your own ppa. Note, that you can copy binaries without rebuild as you don't have to rebuild them at all in vast majority cases, so your ppa will go live in a few minutes, package publishing and indexing is quite fast.

To copy packages, go to PPA where you want copy from, then at the almost top right of the page click on `View package details` and then after new page loaded, almost at the same place click on `Copy packages`. You should be at the `https://launchpad.net/~pinepain/+archive/ubuntu/php/+copy-packages` page now if you copy from `pinepaina/ppa`, for instance. Then pick packages you want to copy, choose target repo and setting below a packages list (same series, copy existing binaries) and voila, you're all done now. 

I can consider to maintain ppa with some older versions or, perhaps, follow stable/testing/unstable releases like Debian does. The only issue is that it becomes a bit time consuming, so without having user base large enough, it may not worth efforts, but I will look into this (thankfully, for me it will be just copying packages like stated above). Anyway, I would hear from you or anyone else who is interested whether adding separate PPAs would be welcomed and necessary.

**Comment by k42b3** [comment]
@pinepain thx for this detailed answer. I have created a new ppa where I maintain a copy of the current php-v8 version:
https://launchpad.net/~k42b3/+archive/ubuntu/php-v8

I will probably switch to your ppa if we are at a stable version but I think it is the best solution for now. So thx again for this great lib!

**Comment by pinepain** [comment]
@k42b3 I'd suggest you to copy current libv8 package in advance as I often upgrade it and newer php-v8 versions depends on newer libv8. Just copy current [pinepain/php](https://launchpad.net/~pinepain/+archive/ubuntu/php) and you'd be fine.

**Comment by k42b3** [comment]
Ok thx, I have copied both libraries, the docker installation works now as expected. I will close this issue since everything is resolved.
