### ISSUE TITLE
CreateDefaultPlatform is deprecated warning (V8 6.4.291)

### ISSUE THREAD

**Issue by AlexMasterov** [pinepain/php-v8#80]
"Use NewDefaultPlatform instead".

v8/v8@ffee558e14e28fc8b1f9a3c10ea3615e0d686c7b

**Comment by pinepain** [comment]
For some reason upgrading from `CreateDefaultPlatform()` to `NewDefaultPlatform()`  doesn't work well.

Hello world example throws:
```
/home/vagrant/php-v8/scripts/test_v8/hello_world.cpp:21: undefined reference to `v8::platform::NewDefaultPlatform(int, v8::platform::IdleTaskSupport, v8::platform::InProcessStackDumping, std::unique_ptr<v8::TracingController, std::default_delete<v8::TracingController> >)'
```
Extension itself is unable to load:
```
/home/vagrant/.phpbrew/php/7.2-debug/bin/php: symbol lookup error: /home/vagrant/php-v8/modules/v8.so: undefined symbol: _ZN2v88platform18NewDefaultPlatformEiNS0_15IdleTaskSupportENS0_21InProcessStackDumpingESt10unique_ptrINS_17TracingControllerESt14default_deleteIS4_EE
```
After spending some time on troubleshooting, I think we need more eyes on this. I posted to v8-users mailing list (https://groups.google.com/forum/#!topic/v8-users/Jb1VSouy2Z0).

**Comment by pinepain** [comment]
It came up that the issue was in how libv8 was build (it wasn't build in a relocatable way and thus wasn't quite good for packaging).

**Comment by pinepain** [comment]
Done in #87. Thanks for taking care!

**Comment by AlexMasterov** [comment]
Thank you :+1: 
Happy New Year!
