### ISSUE TITLE
Warning: Calling <<-EOS.undent is deprecated

### ISSUE THREAD

**Issue by baberuth22** [pinepain/php-v8#94]
I see this when installing on Mac High Sierra using brew:

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/pinepain/homebrew-devtools/Formula/v8@6.4.rb:71:in `block in install'
Please report this to the pinepain/devtools tap!

**Comment by pinepain** [comment]
@baberuth22 Thanks for reporting! I'll update [pinepain/devtools](https://github.com/pinepain/homebrew-devtools) tap later this week.

**Comment by pinepain** [comment]
Fixed by https://github.com/pinepain/homebrew-devtools/commit/8b9206598d45cb8ed811292b21cb35033305ab18
